# Настройки в [build] являются глобальными и применяются ко всем контекстам
# при отсутствии более специфичных настроек (настроек для определенных контекстов)
[build]
  # Директория с файлами, которые должны быть прочитаны перед сборкой проекта
  # По умолчанию таковой является корневая директория
  base = "."

  # Директория, содержащая готовые к деплою HTML-файлы и ресурсы.
  # Путь является относительным (базовая директория).
  # В данном случае абсолютный путь будет выглядеть как `root/project/build-output`
  publish = "./templates"

  # Команда для выполнения сборки
  command = "echo 'default context'"

# Производственный контекст (продакшн-ветка)
[context.production]
  publish = "output/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }
